name: pokemon
description: "The Pokemon app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Networking / HTTP / API Clients
  dio: ^5.3.2
  retrofit: ^4.4.0
  pretty_dio_logger: ^1.4.0

  # Serialization / Codegen annotations
  json_annotation: ^4.9.0
  freezed: ^3.1.0
  freezed_annotation: ^3.0.0

  # State management
  riverpod_annotation: ^2.3.3
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  get_it: ^8.2.0

  # UI / Widgets / Layout / Helpers
  intl: ^0.20.2
  flutter_native_splash: ^2.3.2
  flutter_animator: ^3.2.2
  flutter_spinkit: ^5.2.2
  flutter_screenutil: ^5.9.0
  responsive_framework: ^0.1.0
  lazy_load_scrollview: ^1.3.0
  path_provider: ^2.1.1

  # Navigation / Routing
  go_router: ^16.2.1
  stacked_services: ^1.4.0
  dismissible_page: ^1.0.2

  # Media / Cache / Storage
  flutter_svg: ^2.2.0
  flutter_cache_manager: ^3.4.1
  shared_preferences: ^2.2.2
  hive: any

  # Security / Local auth
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Icon / launcher generation
  flutter_launcher_icons: ^0.14.4

  # Code generation / builders
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.9
  riverpod_generator: ^2.6.5
  hive_generator_plus: ^4.0.2


dependency_overrides:
  retrofit: 4.7.2

flutter_native_splash:
  color: "#FFFFF4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/logo/pokeball.png"

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/png/logos/
    - assets/png/avatars/
    - assets/svg/
    - assets/svg/logos/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 400
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 200

    - family: Outfit-black
      fonts:
        - asset: assets/fonts/Outfit-Black.ttf